### ISSUE TITLE
Works locally but not on cloud functions

### ISSUE THREAD

**Issue by nicolasitei** [khaledalam/instagrammer#1]
Hello,

The program works perfectly on my local environment but when I upload it to a cloud functions, it returns an empty array.

I've made a post here: https://stackoverflow.com/questions/63284553/web-scrapper-works-locally-but-doesnt-on-cloud-functions

Let me know if you ever come across that scenario.

Thanks!

**Comment by khaledalam** [comment]
Hi @nicolasitei thank you for the report, there are some new updates can you confirm if everything is working ok with you or not?
